[project]
name = "cmeel-octomap"
version = "1.9.8"
description = "cmeel distribution for OctoMap, An Efficient Probabilistic 3D Mapping Framework Based on Octrees"
readme = "octomap/README.md"
requires-python = ">= 3.8"
license = "BSD-3-Clause"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-octomap"
repository = "https://github.com/cmake-wheel/cmeel-octomap.git"

[build-system]
requires = ["cmeel[build]"]
build-backend = "cmeel.build"
source = "octomap/octomap"
# tests not OK in // : https://github.com/OctoMap/octomap/pull/374
run_tests = false
